### PR TITLE
Transparency mode of mask and brushes, improved fitToScreen, a few bug fixes. Context menu UI update

### PR DESCRIPTION
**Pull request by daswer123**
In this pr I made:

https://github.com/daswer123/canvas-zoom-showcase - You can see all the possibilities of expansion through video

**1) a mode of transparency of the mask and brush, hotkeys to switch the mode can be enabled in the context menu, as well as there you can adjust the degree of transparency.** 

https://user-images.githubusercontent.com/22278673/230669127-c8a79603-2855-4282-8567-f89b5e52e2ec.mp4

**2) I updated the context menu so that the hotkeys would be grouped by category for convenience.** 

https://user-images.githubusercontent.com/22278673/230669233-e3f32c53-4b05-4564-b204-2487cd2d66ed.mp4

**3) Improved the zoom function on S , fitToScreen, now if the picture does not fit in the window, when you click on the hotkey, it is increased to its full width and fits into the screen.**

https://user-images.githubusercontent.com/22278673/230669340-d66dcdf8-a4fb-47d6-9b9e-87ea9e0fbd4c.mp4

### CODE REVIEW

**Comment by richrobber2** [comment]
looks good, merging

**Comment by richrobber2** [comment]
copilot:summary

**Comment by richrobber2** [comment]
the opacity seems to be pretty buggy when painting with the opacity toggles then toggling again it causes some to disappear, the logic is too confusing for me to figure it out, alternatively it could just be the canvas messing with things again, such a pain...

**Comment by richrobber2** [comment]
@daswer123 for the message above not sure if u are watching this, or if it notifies you anyways so @ing you

**Comment by daswer123** [comment]
@richrobber2 
I keep track of any changes in this repo, so I can see everything )


About opacity:
This is a bad solution, I know, but for it to work properly you need to have access to an array of lines that are set and processed through python scripts. There is no JS access to the array of lines, so I had to come up with a crutch way. 

The bottom line is that in canvas there is a property globalAlpha, which sets the transparency of the lines and to see the changes, you need to update all the lines. Since there is no access to the lines on the kanvas, the only way to do this is to undo. Undo removes the last line and redraws the other lines, thus updating the canvas. 

My solution is that we create a fake click on canvas that creates the line, then change the globalAlpha and undo the click, thus showing the user the transparency of the mask.

The problem with making the last line disappear is that when we switch from transparency to normal mode, it is the next-to-last line that is cancelled, not the last one. I decided that you can do 2 clicks, which creates more lines to undo, but makes line undo less likely, but as you can see it still undoes.

Despite the bugs, it works :D

**Comment by johnwilliamx** [comment]
Hey bor,I need your help,Why did I install it but there is no response,is the latest version，Confused.

**Comment by daswer123** [comment]
Hi, @johnwilliamx 

Create a new issue, and please write there things that I will write below:

1) Check the scale in your browser it should be 100%
2) Can you show the webui version?
image
3) Can you tell me what browser and version you have?
4) Can you show me the console with tab
 inpaint? 
5) Can you show me a list of extensions?

Sorry if it's too much to ask, you just aren't the first one to talk about it and I want to understand the problem.

**Comment by johnwilliamx** [comment]
1.The scale in the browser is 100%
image
2.I don't know the version number either,But I can't use many 2.0 mods so In most cases, 1.5 mods are used
image
3.I have Chorme and Edge new version
4.I don't understand what is tabinpaint
5.
image
I saw someone using your mod in youtube, I like it very much, thank you for answering my questions

**Comment by daswer123** [comment]
@johnwilliamx It's very strange that you don't have a commit hash, try updating manually via git pull

**Pull request merged**
